/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package exshopping.view;

import exshopping.controller.AuthenticationController;
import exshopping.controller.UserController;
import static exshopping.controller.UserController.getAllUsers;
import java.awt.Window;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanbid
 */
public class AdminUserFrame extends javax.swing.JPanel {

	/**
	 * Creates new form ResellerFrame
	 */
	public AdminUserFrame() {
		initComponents();
		populateUserTable();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        remove_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        id_input = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        password_input = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        role_input = new javax.swing.JTextField();
        fetch_btn1 = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Iosevka NFM ExtraLight", 1, 36)); // NOI18N
        jLabel2.setText("Users");

        jLabel10.setFont(new java.awt.Font("Iosevka NFM ExtraLight", 1, 24)); // NOI18N
        jLabel10.setText("username");

        username_input.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        username_input.setText("xxx");
        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });

        remove_btn.setFont(new java.awt.Font("Iosevka NFP SemiBold", 0, 24)); // NOI18N
        remove_btn.setText("Remove ");
        remove_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remove_btnMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Iosevka NFM ExtraLight", 1, 36)); // NOI18N
        jLabel11.setText("ID:");

        id_input.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        id_input.setText("xxx");
        id_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_inputActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Iosevka NFM ExtraLight", 1, 24)); // NOI18N
        jLabel12.setText("role:");

        name_input.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        name_input.setText("xxx");
        name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inputActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Iosevka NFM ExtraLight", 1, 24)); // NOI18N
        jLabel13.setText("name");

        password_input.setColumns(20);
        password_input.setRows(5);
        jScrollPane2.setViewportView(password_input);

        jLabel14.setFont(new java.awt.Font("Iosevka NFM ExtraLight", 1, 24)); // NOI18N
        jLabel14.setText("password");

        role_input.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        role_input.setText("xxx");
        role_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_inputActionPerformed(evt);
            }
        });

        fetch_btn1.setFont(new java.awt.Font("Iosevka NFP SemiBold", 0, 24)); // NOI18N
        fetch_btn1.setText("Fetch");
        fetch_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fetch_btn1MouseClicked(evt);
            }
        });

        update_btn.setFont(new java.awt.Font("Iosevka NFP SemiBold", 0, 24)); // NOI18N
        update_btn.setText("Update User");
        update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_btnMouseClicked(evt);
            }
        });

        add_btn.setFont(new java.awt.Font("Iosevka NFP SemiBold", 0, 24)); // NOI18N
        add_btn.setText("Add User");
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });
        add_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                add_btnKeyTyped(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(username_input, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(remove_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(id_input, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(name_input, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(role_input, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(fetch_btn1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(update_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(add_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(role_input, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel13)
                                    .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(remove_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(174, 174, 174))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(441, Short.MAX_VALUE)
                    .addComponent(fetch_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(221, 221, 221)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addGap(75, 75, 75)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(role_input, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn)
                    .addComponent(update_btn)
                    .addComponent(remove_btn))
                .addContainerGap(302, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(196, 196, 196)
                    .addComponent(fetch_btn1)
                    .addContainerGap(928, Short.MAX_VALUE)))
        );

        jLabel5.setFont(new java.awt.Font("Iosevka NFM ExtraLight", 1, 36)); // NOI18N
        jLabel5.setText("Total Users");

        user_table.setFont(new java.awt.Font("Iosevka NF", 0, 29)); // NOI18N
        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        user_table.setRowHeight(60);
        jScrollPane1.setViewportView(user_table);

        jDesktopPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif.plain", 0, 36)); // NOI18N
        jLabel1.setText("Admin Page");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(756, 756, 756))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

    private void id_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_inputActionPerformed

    private void name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_inputActionPerformed

    private void role_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_role_inputActionPerformed

    private void fetch_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fetch_btn1MouseClicked
		try {
			// Try parsing user ID first
			int userId = Integer.parseInt(id_input.getText());

			if (userId <= 0){
				JOptionPane.showMessageDialog(this, "Invalid num", "Error", JOptionPane.ERROR_MESSAGE);
			}

			Object[] userData = UserController.getUserById(userId);

			if (userData.length > 0) {
				name_input.setText((String) userData[1]);
				username_input.setText((String) userData[2]);
				role_input.setText((String) userData[4]);
				password_input.setText((String) userData[3]); 

				JOptionPane.showMessageDialog(this, "User found", "Success", JOptionPane.INFORMATION_MESSAGE);
			} else {
				JOptionPane.showMessageDialog(this, "User not found", "Error", JOptionPane.ERROR_MESSAGE);
				clearInputFields();
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "Please enter a valid User ID", "Error", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_fetch_btn1MouseClicked

    private void add_btnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_btnKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_add_btnKeyTyped

    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        // TODO add your handling code here:

		// Get input values
		String name = name_input.getText().trim();
		String username = username_input.getText().trim();
		String password = password_input.getText().trim();
		String role = role_input.getText().trim();

		// Validation checks
		if (name.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Name cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
			name_input.requestFocus();
			return;
		}

		if (username.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Username cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
			username_input.requestFocus();
			return;
		}

		if (password.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Password cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
			password_input.requestFocus();
			return;
		}

		if (role.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Role cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
			role_input.requestFocus();
			return;
		}

		// Additional validations
		if (name.length() < 2) {
			JOptionPane.showMessageDialog(this, "Name must be at least 2 characters long", "Validation Error", JOptionPane.ERROR_MESSAGE);
			name_input.requestFocus();
			return;
		}

		if (username.length() < 4) {
			JOptionPane.showMessageDialog(this, "Username must be at least 4 characters long", "Validation Error", JOptionPane.ERROR_MESSAGE);
			username_input.requestFocus();
			return;
		}

		if (password.length() < 6) {
			JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long", "Validation Error", JOptionPane.ERROR_MESSAGE);
			password_input.requestFocus();
			return;
		}

		// Attempt to create user
		boolean userCreated = UserController.createUser(name, username, password, role);

		if (userCreated) {
			JOptionPane.showMessageDialog(this, "User created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
			// Clear input fields after successful creation
			clearInputFields();
populateUserTable();
		} else {
			JOptionPane.showMessageDialog(this, "Failed to create user", "Error", JOptionPane.ERROR_MESSAGE);
		}
		
    }//GEN-LAST:event_add_btnMouseClicked

    private void update_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_btnMouseClicked
        // TODO add your handling code here:

		int userID = Integer.parseInt(id_input.getText());

		String name = name_input.getText().trim();
		String username = username_input.getText().trim();
		String password = password_input.getText().trim();
		String role = role_input.getText().trim();

		if (name.isEmpty() || username.isEmpty() || role.isEmpty()) {
			JOptionPane.showMessageDialog(this, "All fields must be filled", "Validation Error", JOptionPane.ERROR_MESSAGE);
			return;
		}

		 String hashedPassword = AuthenticationController.hashPassword(password);

		boolean userUpdated = UserController.updateUser(userID, name, username, role, hashedPassword);

		if (userUpdated) {
			JOptionPane.showMessageDialog(this, "User updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
populateUserTable();
			clearInputFields();
		} else {
			JOptionPane.showMessageDialog(this, "Failed to update user", "Error", JOptionPane.ERROR_MESSAGE);
		}
		
    }//GEN-LAST:event_update_btnMouseClicked

	private void populateUserTable() {
		List<Object[]> users = getAllUsers();


		String[] columnNames = {"ID", "Name", "Username", "Password", "Created At", "Role"};

		DefaultTableModel model = new DefaultTableModel(columnNames, 0);

		for (Object[] user : users) {
			model.addRow(user);
		}
		user_table.setModel(model);
	}



    private void remove_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remove_btnMouseClicked
        // TODO add your handling code here:
		int userID = Integer.parseInt(id_input.getText());



		boolean deletedUser = UserController.deleteUser(userID);

		if (deletedUser) {
			JOptionPane.showMessageDialog(this, "User removed successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
			clearInputFields();
populateUserTable();
		} else {
			JOptionPane.showMessageDialog(this, "Failed to removed user", "Error", JOptionPane.ERROR_MESSAGE);
		}	
    }//GEN-LAST:event_remove_btnMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        AdminPage admin = new AdminPage();
        frame.add(admin);
        frame.pack();
        frame.setVisible(true);
        closePanel();
    }//GEN-LAST:event_jLabel1MouseClicked

	public void closePanel() {
		Window window = SwingUtilities.getWindowAncestor(this);
		if (window != null) {
			window.dispose();
		}
	}


	private void clearInputFields() {
		name_input.setText("");
		username_input.setText("");
		password_input.setText("");
		role_input.setText("");
	}





	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		System.out.println("ResellerFrame running...");
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

				JFrame frame = new JFrame("Reseller");
				AdminUserFrame panel = new AdminUserFrame();
				frame.add(panel);
				frame.pack();
				frame.setVisible(true);
			}
		});
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton fetch_btn1;
    private javax.swing.JTextField id_input;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name_input;
    private javax.swing.JTextArea password_input;
    private javax.swing.JButton remove_btn;
    private javax.swing.JTextField role_input;
    private javax.swing.JButton update_btn;
    private javax.swing.JTable user_table;
    private javax.swing.JTextField username_input;
    // End of variables declaration//GEN-END:variables
}
