/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exshopping.view;

import exshopping.controller.DiscountController;
import static exshopping.controller.DiscountController.getAllDiscountCodes;
import exshopping.model.DiscountCode;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanbid
 */
public class DiscountCodes extends javax.swing.JFrame {

	/**
	 * Creates new form DIscountCodes
	 */
	public DiscountCodes() {
		initComponents();
		populateDiscountTable();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        max_usage_input = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        discount_code_input = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        percentage_input = new javax.swing.JTextField();
        remove_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        discount_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        jLabel1.setText("Discount Codes");

        jLabel9.setFont(new java.awt.Font("Iosevka NF", 0, 24)); // NOI18N
        jLabel9.setText(" max_usage ");

        max_usage_input.setText("max_usage...");

        jLabel10.setFont(new java.awt.Font("Iosevka NF", 0, 24)); // NOI18N
        jLabel10.setText("Discount Codes");

        discount_code_input.setText("code ..");

        jLabel11.setFont(new java.awt.Font("Iosevka NF", 0, 24)); // NOI18N
        jLabel11.setText("percentage");

        percentage_input.setText("percentage...");

        remove_btn.setText("REMOVE");
        remove_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                remove_btnMouseExited(evt);
            }
        });
        remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_btnActionPerformed(evt);
            }
        });

        add_btn.setText("ADD");
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(max_usage_input, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(discount_code_input, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(percentage_input, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(remove_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(add_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(max_usage_input)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(remove_btn))
                    .addComponent(percentage_input)
                    .addComponent(discount_code_input)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(0, 223, Short.MAX_VALUE)))
                .addGap(184, 184, 184))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(add_btn)
                    .addContainerGap(525, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(150, 150, 150)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discount_code_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(percentage_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(max_usage_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(remove_btn)
                .addContainerGap(381, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(697, Short.MAX_VALUE)
                    .addComponent(add_btn)
                    .addGap(357, 357, 357)))
        );

        jLabel3.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        jLabel3.setText("0");

        discount_table.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        discount_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "code", "percentage", "max usage", "current usage"
            }
        ));
        discount_table.setAlignmentX(1.5F);
        discount_table.setAlignmentY(1.5F);
        discount_table.setRowHeight(60);
        discount_table.setRowMargin(10);
        jScrollPane1.setViewportView(discount_table);

        jLabel4.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        jLabel4.setText("All Codes");

        jLabel5.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        jLabel5.setText("Total used code:");

        jLabel6.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        jLabel6.setText("Codes");

        jLabel7.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        jLabel7.setText("0");

        jLabel8.setFont(new java.awt.Font("Iosevka NF", 0, 36)); // NOI18N
        jLabel8.setText("Total codes:");

        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel6)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addGap(101, 101, 101)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif.plain", 0, 36)); // NOI18N
        jLabel2.setText("Admin Page");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(634, 634, 634))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void remove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remove_btnActionPerformed

    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        // TODO add your handling code here:
 String code = discount_code_input.getText().trim();
		String percentageStr = percentage_input.getText().trim();
		String maxUsageStr = max_usage_input.getText().trim();

		// Validate discount code
		if (code.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Discount code cannot be empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
			discount_code_input.requestFocus();
			return;
		}

		// Validate percentage
		double percentage;
		try {
			percentage = Double.parseDouble(percentageStr);
			if (percentage <= 0 || percentage > 100) {
				JOptionPane.showMessageDialog(this, "Percentage must be between 0 and 100", "Validation Error", JOptionPane.ERROR_MESSAGE);
				percentage_input.requestFocus();
				return;
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "Invalid percentage value", "Validation Error", JOptionPane.ERROR_MESSAGE);
			percentage_input.requestFocus();
			return;
		}

		// Validate max usage
		int maxUsage;
		try {
			maxUsage = Integer.parseInt(maxUsageStr);
			if (maxUsage <= 0) {
				JOptionPane.showMessageDialog(this, "Max usage must be a positive number", "Validation Error", JOptionPane.ERROR_MESSAGE);
				max_usage_input.requestFocus();
				return;
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "Invalid max usage value", "Validation Error", JOptionPane.ERROR_MESSAGE);
			max_usage_input.requestFocus();
			return;
		}

		// Attempt to create discount code
		boolean discountCreated = DiscountController.createDiscountCode(code, percentage, maxUsage);

		if (discountCreated) {
			JOptionPane.showMessageDialog(this, "Discount code created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

			// Clear input fields after successful creation
			clearInputFields();
			populateDiscountTable();
		} else {
			JOptionPane.showMessageDialog(this, "Failed to create discount code", "Error", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_add_btnMouseClicked

    private void remove_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remove_btnMouseExited
        // TODO add your handling code here:
		String code_text = discount_code_input.getText();

		if(code_text.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Failed to create discount code", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}

		if(DiscountController.deleteDiscountCode(code_text)) {
			JOptionPane.showMessageDialog(this, "Sucessfully removed!!", "Success", JOptionPane.INFORMATION_MESSAGE);
			clearInputFields();
			populateDiscountTable();
		}else {
			JOptionPane.showMessageDialog(this, "Sucessfully removed!!", "Error", JOptionPane.ERROR_MESSAGE);
		}

    }//GEN-LAST:event_remove_btnMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        AdminPage admin = new AdminPage();
        frame.add(admin);
        frame.pack();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked


	// Helper method to clear input fields
	private void clearInputFields() {
		discount_code_input.setText("");
		percentage_input.setText("");
		max_usage_input.setText("");
	}

	private void populateDiscountTable() {
		List<DiscountCode> discountCodes = getAllDiscountCodes();

		// Define column names
		String[] columnNames = {"Discount Code", "Percentage", "Max Usage", "Current Usage"};

		// Create a default table model
		DefaultTableModel model = new DefaultTableModel(columnNames, 0);

		// Populate the model with data
		for (DiscountCode code : discountCodes) {
			Object[] rowData = {
				code.getCode(),
				code.getPercentage() + "%",
				code.getMaxUsage(),
				code.getCurrentUsage()
			};
			model.addRow(rowData);
		}

		// Set the model to the table
		discount_table.setModel(model);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DiscountCodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DiscountCodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DiscountCodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DiscountCodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DiscountCodes().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField discount_code_input;
    private javax.swing.JTable discount_table;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField max_usage_input;
    private javax.swing.JTextField percentage_input;
    private javax.swing.JButton remove_btn;
    // End of variables declaration//GEN-END:variables
}
