/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exshopping.view;

import exshopping.controller.AuthenticationController;
import exshopping.controller.CartController;
import exshopping.controller.Product;
import exshopping.controller.ProductController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author sanbid
 */
public class HomeFrame extends javax.swing.JFrame {

	/**
	 * Creates new form HomeFrame
	 */
	public HomeFrame() {
		initComponents();
		displayProducts();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        login_btn = new javax.swing.JLabel();
        Home_btn = new javax.swing.JLabel();
        contact_btn = new javax.swing.JLabel();
        about_btn = new javax.swing.JLabel();
        search_input = new javax.swing.JTextField();
        profile_btn = new javax.swing.JButton();
        search_btn1 = new javax.swing.JButton();
        addcart_btn1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        women_btn = new javax.swing.JButton();
        Man_btn = new javax.swing.JButton();
        Electronic_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_panel = new javax.swing.JPanel();
        product_frame = new javax.swing.JDesktopPane();
        product_image = new javax.swing.JLabel();
        product_name = new javax.swing.JLabel();
        product_prices = new javax.swing.JLabel();
        addcart_product_1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login_btn.setFont(new java.awt.Font("SansSerif.plain", 1, 24)); // NOI18N
        login_btn.setText("Ex Shopping");

        Home_btn.setText("Home");
        Home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_btnMouseClicked(evt);
            }
        });

        contact_btn.setText("Contact");

        about_btn.setText("About");
        about_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about_btnMouseClicked(evt);
            }
        });

        search_input.setFont(new java.awt.Font("SansSerif.plain", 0, 18)); // NOI18N
        search_input.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        search_input.setText("what are you looking for ?");
        search_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_inputActionPerformed(evt);
            }
        });

        profile_btn.setText("");
        profile_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_btnMouseClicked(evt);
            }
        });

        search_btn1.setText("");

        addcart_btn1.setText("");
        addcart_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcart_btn1MouseClicked(evt);
            }
        });

        jButton1.setText("health");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        women_btn.setText("Women fashion");

        Man_btn.setText("Man Fashion");
        Man_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Man_btnActionPerformed(evt);
            }
        });

        Electronic_btn.setText("electronic");
        Electronic_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Electronic_btnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frame.png"))); // NOI18N

        product_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product.png"))); // NOI18N
        product_image.setText("jLabel2");

        product_name.setText("product name");

        product_prices.setText("prices");

        addcart_product_1.setText("Add Cart");
        addcart_product_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcart_product_1ActionPerformed(evt);
            }
        });

        product_frame.setLayer(product_image, javax.swing.JLayeredPane.DEFAULT_LAYER);
        product_frame.setLayer(product_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        product_frame.setLayer(product_prices, javax.swing.JLayeredPane.DEFAULT_LAYER);
        product_frame.setLayer(addcart_product_1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout product_frameLayout = new javax.swing.GroupLayout(product_frame);
        product_frame.setLayout(product_frameLayout);
        product_frameLayout.setHorizontalGroup(
            product_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_frameLayout.createSequentialGroup()
                .addGroup(product_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(product_frameLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(product_image, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(product_frameLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(product_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(product_prices)
                            .addComponent(product_name)
                            .addComponent(addcart_product_1))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        product_frameLayout.setVerticalGroup(
            product_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_frameLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(product_image, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(product_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(product_prices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addcart_product_1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout product_panelLayout = new javax.swing.GroupLayout(product_panel);
        product_panel.setLayout(product_panelLayout);
        product_panelLayout.setHorizontalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(product_frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1002, Short.MAX_VALUE))
        );
        product_panelLayout.setVerticalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(product_frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(product_panel);

        jLabel2.setFont(new java.awt.Font("SansSerif.plain", 1, 36)); // NOI18N
        jLabel2.setText("Sales");

        jLabel3.setFont(new java.awt.Font("SansSerif.plain", 1, 24)); // NOI18N
        jLabel3.setText("Category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(login_btn)
                .addGap(274, 274, 274)
                .addComponent(Home_btn)
                .addGap(46, 46, 46)
                .addComponent(contact_btn)
                .addGap(47, 47, 47)
                .addComponent(about_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(addcart_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Man_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(women_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Electronic_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1221, Short.MAX_VALUE)
                    .addComponent(search_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(237, 237, 237)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(about_btn)
                    .addComponent(contact_btn)
                    .addComponent(Home_btn)
                    .addComponent(login_btn)
                    .addComponent(addcart_btn1)
                    .addComponent(profile_btn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3)
                        .addGap(65, 65, 65)
                        .addComponent(women_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Man_btn)
                        .addGap(33, 33, 33)
                        .addComponent(Electronic_btn)
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addGap(123, 123, 123)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(search_btn1)
                    .addContainerGap(1240, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_inputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Man_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Man_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Man_btnActionPerformed

    private void Electronic_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Electronic_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Electronic_btnActionPerformed

    private void addcart_product_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcart_product_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addcart_product_1ActionPerformed

    private void addcart_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcart_btn1MouseClicked
        // TODO add your handling code here:
		new AddCartFrame().setVisible(true);
		this.dispose();
    }//GEN-LAST:event_addcart_btn1MouseClicked

    private void profile_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_btnMouseClicked
        // TODO add your handling code here:
		new Profile().setVisible(true);
		this.dispose();

    }//GEN-LAST:event_profile_btnMouseClicked

    private void about_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_btnMouseClicked
        // TODO add your handling code here:
		new ResellerFrame().setVisible(true);
    }//GEN-LAST:event_about_btnMouseClicked

    private void Home_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_btnMouseClicked
        // TODO add your handling code here:
		new HomeFrame().setVisible(true);
    }//GEN-LAST:event_Home_btnMouseClicked

	public void displayProducts() {
		product_frame.removeAll();

		List<Product> products = ProductController.fetchAllProducts();
		System.out.print(products);

		// Set layout for dynamic product display
		product_frame.setLayout(new GridLayout(0, 3, 10, 10)); // 3 columns, with gaps

		for (Product product : products) {

			// Create a panel for each product
			JPanel productPanel = new JPanel();
			productPanel.setLayout(new BorderLayout());

			productPanel.setBorder(BorderFactory.createEmptyBorder(10, 25, 10, 25)); // 10px top/bottom, 15px left/right

			File baseDir = new File(".");
			ImageIcon imageIcon = new ImageIcon(baseDir.getAbsolutePath() + "/src/exshopping/product_images/" + product.getImagePath());
			Image scaledImage = imageIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
			JLabel imageLabel = new JLabel(new ImageIcon(scaledImage));
			imageLabel.setHorizontalAlignment(SwingConstants.CENTER);

			// Product Name
			JLabel nameLabel = new JLabel(product.getProductName());
			nameLabel.setHorizontalAlignment(SwingConstants.LEFT);

			// Product Price
			JLabel priceLabel = new JLabel("$" + String.format("%.2f", product.getPrice()));
			priceLabel.setHorizontalAlignment(SwingConstants.CENTER);


			// Product Image

			// Add to Cart Button
			JButton addToCartButton = new JButton("Add to Cart");
			addToCartButton.setPreferredSize(new Dimension(150, 40));
			addToCartButton.addActionListener(e -> {
				int userID = AuthenticationController.getUserId();
				CartController.addToCart(userID, product.getProductId(), 1);
			});


			// Assemble product panel
			productPanel.setBackground(new Color(0x26, 0x26, 0x26)); // Dark gray background
			productPanel.add(imageLabel, BorderLayout.NORTH);
			productPanel.add(nameLabel, BorderLayout.CENTER);
			productPanel.add(priceLabel, BorderLayout.EAST);
			productPanel.add(addToCartButton, BorderLayout.SOUTH);

			// Add to main product frame
			product_frame.add(productPanel);
		}

		// Refresh the frame
		product_frame.revalidate();
		product_frame.repaint();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				HomeFrame hf = new HomeFrame();
				hf.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Electronic_btn;
    public javax.swing.JLabel Home_btn;
    private javax.swing.JButton Man_btn;
    public javax.swing.JLabel about_btn;
    public javax.swing.JButton addcart_btn1;
    private javax.swing.JButton addcart_product_1;
    public javax.swing.JLabel contact_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel login_btn;
    private javax.swing.JDesktopPane product_frame;
    public javax.swing.JLabel product_image;
    public javax.swing.JLabel product_name;
    private javax.swing.JPanel product_panel;
    public javax.swing.JLabel product_prices;
    public javax.swing.JButton profile_btn;
    public javax.swing.JButton search_btn1;
    public javax.swing.JTextField search_input;
    private javax.swing.JButton women_btn;
    // End of variables declaration//GEN-END:variables
}
